### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 7 and 64. Shapes are [7,7,448,64] and [64,3,7,7]. for 'Assign' (op: 'Assign') with input shapes: [7,7,448,64], [64,3,7,7].

### ISSUE THREAD

**Issue by zz10001** [iamhankai/attribute-aware-attention#12]
when i run run.sh.it happened.what should i do?

**Comment by iamhankai** [comment]
It seemss that one of the input has wrong shape. 64 is the batch size, it should at the 1st dimension.

**Comment by iamhankai** [comment]
I guess you should change "image_data_format" in $HOME/.keras/keras.json

**Comment by zz10001** [comment]
thx，i will try it。
