### ISSUE TITLE
inconsistence about final feature between paper and code?

### ISSUE THREAD

**Issue by hiyijian** [iamhankai/attribute-aware-attention#2]
Dear @iamhankai ,
   Final feature equals region feature plus attr feature in your paper, while its equals concat of the two in your code. Is there any experiment shows which is better?

**Comment by iamhankai** [comment]
> Dear @iamhankai ,
> Final feature equals region feature plus attr feature in your paper, while its equals concat of the two in your code. Is there any experiment shows which is better?

Yes, we have tried two manners, and there is no significant difference.

**Comment by hiyijian** [comment]
@iamhankai Thanks
