### ISSUE TITLE
How you are deciding this value 11788? and what does it mean?

### ISSUE THREAD

**Issue by chandanmishra-03** [iamhankai/attribute-aware-attention#3]
# transform binary attribute to clustered attribute
nb_attr = len(start_idxs)-1
A_all = np.zeros((**11788**,nb_attr))
image_attribute_file = '../CUB_200_2011/attributes/image_attribute_labels.txt'

**Comment by iamhankai** [comment]
> # transform binary attribute to clustered attribute
> nb_attr = len(start_idxs)-1
> A_all = np.zeros((**11788**,nb_attr))
> image_attribute_file = '../CUB_200_2011/attributes/image_attribute_labels.txt'

11788 is the number of training samples.
