### ISSUE TITLE
emb_dim in code is 512 but not 2048?

### ISSUE THREAD

**Issue by prologueyan-hr** [iamhankai/attribute-aware-attention#5]

**Comment by iamhankai** [comment]
https://github.com/iamhankai/attribute-aware-attention/blob/ab3210705524bcb56f0121de0bcd47f3f93fb6c5/cub_demo.py#L39

512 is for VGG-16, 2048 is for ResNet-50.

**Comment by prologueyan-hr** [comment]
I mean emb_dim
`emb_dim = 512`

**Comment by iamhankai** [comment]
> I mean emb_dim
> `emb_dim = 512`

Sorry, my fault. The length of embedding is not important. The performance is similar.
